version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.1.3
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
  - dependency-name: puma
    versions:
    - 5.2.0
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: browser
    versions:
    - 5.3.0
  - dependency-name: sdoc
    versions:
    - 2.0.3
  - dependency-name: config
    versions:
    - 2.2.3
