scss_files: "**/*.scss"

severity: warning

linters:
  IdSelector:
    enabled: false

  SelectorDepth:
    enabled: false

  SelectorFormat:
    enabled: true
    id_convention: snake_case
    class_convention: hyphenated_lowercase

  ColorVariable:
    enabled: false

  QualifyingElement:
    enabled: false
