version: "2"
services:
  storage:
   image: busybox
   volumes:
     - /var/lib/mysql


  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    volumes_from:
      - storage
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hoge
      POSTGRES_DB: whalebirdorg
    volumes:
      - storage:/var/lib/postgres/data

  rails:
    image: h3poteto/rails:v2.6.3-slim-buster
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
      SERVER_EMAIL: $SERVER_EMAIL
      SERVER_EMAIL_PASSWORD: $SERVER_EMAIL_PASSWORD
      WEB_EMAIL: $WEB_EMAIL
      SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
      DB_USERNAME: root
      DB_PASSWORD: hoge
    volumes:
      - ~/.ssh:/home/rails/.ssh
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mysql:mysql
      - postgres:postgres
    command: /bin/bash

  pgloader:
    image: dimitri/pgloader
    links:
      - mysql:mysql
      - postgres:postgres
    command: /bin/bash

volumes:
  storage:

