version: "2"
services:
  storage:
   image: busybox
   volumes:
     - /var/lib/mysql
  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    volumes_from:
      - storage
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  rails:
    image: h3poteto/rails:v2.3.4
    environment:
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
    env_file: .docker-env
    volumes:
      - ~/.ssh:/home/rails/.ssh
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - mysql:mysql
    command: /bin/bash
