version: '3'
services:
  rails:
    image: 564677439943.dkr.ecr.ap-northeast-1.amazonaws.com/h3poteto/whalebirdorg:latest
    environment:
      DB_HOST: $DB_HOST
      DB_USERNAME: $DB_USERNAME
      DB_PASSWORD: $DB_PASSWORD
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      SERVER_EMAIL: $SERVER_EMAIL
      SERVER_EMAIL_PASSWORD: $SERVER_EMAIL_PASSWORD
      WEB_EMAIL: $WEB_EMAIL
      SLACK_WEBHOOK_URL: $SLACK_WEBHOOK_URL
      # static fileをホスティングするnginxを用意できないのでrailsにホスティングさせる
      RAILS_SERVE_STATIC_FILES: "true"
      PORT: 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3000"]
      interval: 20s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      update_config:
        parallelism: 1
        delay: 20s
    stop_grace_period: 20s
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: ServiceLogs/whalebirdorg
        awslogs-stream: rails
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - rails
    volumes:
      - ./ssl_certs:/var/lib/https-portal
    environment:
      DOMAINS: 'whalebird.org -> http://rails:3000'
      WORKER_PROCESS: 4
      STAGE: 'production'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
    stop_grace_period: 10s
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: ServiceLogs/whalebirdorg
        awslogs-stream: nginx
