default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: <%= ENV["DB_HOST"] || "postgres" %>
  username: <%= ENV["DB_USERNAME"] || "root" %>
  password: <%= ENV["DB_PASSWORD"] %>
  socket: <%= ENV["DB_SOCKET"] %>

development:
  <<: *default
  database: <%= ENV["DB_WHALEBIRD_DEVELOPMENT"] || "whalebirdorg_dev" %>

test:
  <<: *default
  database: <%= ENV["DB_WHALEBIRD_TEST"] || "whalebirdorg_test" %>

production:
  <<: *default
  database: <%= ENV["DB_WHALEBIRD_PORDUCTION"] || "whalebirdorg" %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV['DB_PASSWORD'] %>
